/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    BaseDetails: typeof import('./src/components/BaseDetails.vue')['default']
    BaseProfileForm: typeof import('./src/components/BaseProfileForm.vue')['default']
    DashboardSidebar: typeof import('./src/components/DashboardSidebar.vue')['default']
    InstituteForm: typeof import('./src/components/InstituteForm.vue')['default']
    InstituteItem: typeof import('./src/components/InstituteItem.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    RegisterForm: typeof import('./src/components/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
